version: "3"
networks:
  default:
    driver: bridge
services:
  mockserver-configify:
    container_name: mockserver-configify
    image: mockserver/mockserver
    networks:
      - default
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - ./mockserver.json:/config/initializer.json

  custom-secrets-example:
    container_name: custom-secrets-example
    restart: always
    depends_on:
      - mockserver-configify
    build: ./
    networks:
      - default
    environment:
      MOCK_SERVER_URL: http://mockserver-configify:1080/secrets
      CUSTOM_SECRET_DB_PASSWORD: my-custom-secret-id
    ports:
      - "3000:3000"
